name: Build LaTeX document
on:
  push:
    branches:    
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
      - name: Upload main.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: main.pdf
